data-path="Data"

genesis-file="../genesis.json"

#logging="TRACE"

rpc-http-enabled=true
rpc-http-cors-origins=["*"]
rpc-http-host="192.168.178.21"
host-allowlist=["*"]
rpc-http-api=["ADMIN","ETH","NET","PERM","IBFT","WEB3"]

miner-enabled=true
miner-coinbase="0x0000000000000000000000000000000000000000"
min-gas-price=0

permissions-accounts-contract-enabled=true
permissions-accounts-contract-address="0x0000000000000000000000000000000000008888"
permissions-nodes-contract-enabled=true
permissions-nodes-contract-address="0x0000000000000000000000000000000000009999"
permissions-nodes-contract-version=2
